FROM python:3.6.8-jessie

ADD ./requirements.txt /code/requirements.txt

WORKDIR /code

RUN apt-get update \
    && apt-get install -y build-essential mpich libpq-dev \
    && pip install --progress-bar off --requirement pytest
    && pip install --progress-bar off --requirement requirements.txt
